function S=analyticSource2D(S)
g=9.81;
c=1;
% s1 = @(x,y,t,U) -c*sin(c*t-x).*cos(c*t-y)-cos(c*t-x).*c.*sin(c*t-y)+cos(c*t-x)+cos(c*t-y);
% s2 = @(x,y,t,U) -cos(-x+t)-sin(-x+t).^3.*cos(-y+t)./(cos(-x+t).*cos(-y+t)+2).^2 ...
%                -2*sin(-x + t).*cos(-x + t)./(cos(-x + t).*cos(-y + t) + 2) ...
%                +g*(cos(-x + t).*cos(-y + t) + 2).*sin(-x + t).*cos(-y + t) ...
%                -sin(-y + t).^2.*sin(-x + t).*cos(-x + t)./(cos(-x + t).*cos(-y + t) + 2).^2 ...
%                -cos(-y + t).*sin(-x + t)./(cos(-x + t).*cos(-y + t) + 2);
% s3 = @(x,y,t,U) -cos(-y + t) - sin(-y + t).*sin(-x + t).^2.*cos(-y + t)./(cos(-x + t).*cos(-y + t) + 2).^2 ... 
%               - sin(-y + t).*cos(-x + t)./(cos(-x + t).*cos(-y + t) + 2)...
%               - sin(-y + t).^3.*cos(-x + t)./(cos(-x + t).*cos(-y + t) + 2).^2 ...
%               - 2*sin(-y + t).*cos(-y + t)./(cos(-x + t).*cos(-y + t) + 2) ...
%               + g*(cos(-x + t).*cos(-y + t) + 2).*cos(-x + t).*sin(-y + t);

s1 = @(x,y,t,U) 0;
s2 = @(x,y,t,U) 0;
s3 = @(x,y,t,U) 0;

S.source = @(x,y,t,U) cat(3,s1(x,y,t,U),s2(x,y,t,U),s3(x,y,t,U));

end